from typing import Dict
from .models import (
    ChannelProfile,
    VideoItem,
    HookForensics,
    RetentionPacing,
    DirectorScriptRow,
    ThumbnailStrategy,
    MultiPlatformAssets,
    VideoDossier,
    ChannelDossierResponse,
    ViralityBreakdown,
    NextViralPlaybook,
)

SAMPLE_CREATORS: Dict[str, ChannelDossierResponse] = {
    "mkbhd": ChannelDossierResponse(
        channel=ChannelProfile(
            handle="@MKBHD",
            title="Marques Brownlee",
            description="Quality Tech Videos | YouTuber | Geek | Consumer Tech Authority",
            avatar="https://yt3.googleusercontent.com/lkH37D712tiyphnu0Id0D5MwwQ7IRuwgQLVD05iMXlCFyjYLeYTZ7Occ6AqjyLnzucUGQnnh=s176-c-k-c0x00ffffff-no-rj",
            subscriber_count="18.9M",
            total_videos_analyzed=42,
            median_views=2150000,
            formatted_median_views="2.15M",
            viral_breakout_rate="7.1%",
            niche="Consumer Tech & Hardware",
        ),
        videos=[
            VideoItem(
                id="v-_d2e7x4KA",
                title="The Wildest Camera Robot",
                url="https://www.youtube.com/watch?v=v-_d2e7x4KA",
                views=14800000,
                formatted_views="14.8M",
                thumbnail="https://i.ytimg.com/vi/v-_d2e7x4KA/hqdefault.jpg",
                published_at="Feb 2024",
                is_short=False,
                outlier_score=6.88,
                is_outlier=True,
                is_mega_viral=True,
                outlier_badge="Mega Outlier 🚀 (6.9x)",
            ),
            VideoItem(
                id="ngPkbaZliaU",
                title="The Truth About the Bezelless Phone",
                url="https://www.youtube.com/watch?v=ngPkbaZliaU",
                views=6400000,
                formatted_views="6.4M",
                thumbnail="https://i.ytimg.com/vi/ngPkbaZliaU/hqdefault.jpg",
                published_at="May 2024",
                is_short=False,
                outlier_score=2.98,
                is_outlier=True,
                is_mega_viral=False,
                outlier_badge="Viral Breakout 🔥 (3.0x)",
            ),
            VideoItem(
                id="mfmdXPT7nAM",
                title="I Said Yes to Every Email for a Month!",
                url="https://www.youtube.com/watch?v=mfmdXPT7nAM",
                views=3900000,
                formatted_views="3.9M",
                thumbnail="https://i.ytimg.com/vi/mfmdXPT7nAM/hqdefault.jpg",
                published_at="Aug 2024",
                is_short=False,
                outlier_score=1.82,
                is_outlier=False,
                is_mega_viral=False,
                outlier_badge="Above Average",
            ),
            VideoItem(
                id="1Psh_r2sYfE",
                title="Galaxy Z Fold 8 Review: Honeymoon's Over",
                url="https://www.youtube.com/watch?v=1Psh_r2sYfE",
                views=4620000,
                formatted_views="4.6M",
                thumbnail="https://i.ytimg.com/vi/1Psh_r2sYfE/hqdefault.jpg",
                published_at="Jan 2024",
                is_short=False,
                outlier_score=2.15,
                is_outlier=True,
                is_mega_viral=False,
                outlier_badge="Viral Breakout 🔥",
            ),
        ],
        top_outliers=[
            VideoItem(
                id="outlier_mkbhd_1",
                title="Apple Vision Pro: 24 Hours Later! (The Honest Truth)",
                url="https://www.youtube.com/watch?v=dtp6bRe6x3U",
                views=14800000,
                formatted_views="14.8M",
                thumbnail="https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=640&auto=format&fit=crop&q=80",
                published_at="Feb 2024",
                is_short=False,
                outlier_score=6.88,
                is_outlier=True,
                is_mega_viral=True,
                outlier_badge="Mega Outlier 🚀 (6.9x)",
            ),
            VideoItem(
                id="mkbhd_5",
                title="Humane AI Pin: The Review Nobody Wanted",
                url="https://www.youtube.com/watch?v=example5",
                views=8900000,
                formatted_views="8.9M",
                thumbnail="https://images.unsplash.com/photo-1518770660439-4636190af475?w=640&auto=format&fit=crop&q=80",
                published_at="Apr 2024",
                is_short=False,
                outlier_score=4.14,
                is_outlier=True,
                is_mega_viral=False,
                outlier_badge="Viral Breakout 🔥 (4.1x)",
            ),
        ],
        active_dossier=VideoDossier(
            video=VideoItem(
                id="outlier_mkbhd_1",
                title="Apple Vision Pro: 24 Hours Later! (The Honest Truth)",
                url="https://www.youtube.com/watch?v=dtp6bRe6x3U",
                views=14800000,
                formatted_views="14.8M",
                thumbnail="https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=640&auto=format&fit=crop&q=80",
                published_at="Feb 2024",
                is_short=False,
                outlier_score=6.88,
                is_outlier=True,
                is_mega_viral=True,
                outlier_badge="Mega Outlier 🚀 (6.9x)",
            ),
            hook_forensics=HookForensics(
                first_3_seconds_visual="MKBHD sitting silently wearing the massive headset, staring deadpan directly into the camera lens with zero audio for 1.2 seconds, then taking it off with an audible sigh.",
                first_3_seconds_audio="\"So... I just spent 24 straight hours inside of Apple's $3,500 computer on my face. And I have some bad news.\"",
                primary_psychological_trigger="Negative Anticipation & High Stakes Novelty",
                trigger_explanation="Rather than hyping Apple's tech, he used an extreme anti-hype pattern: silence -> sigh -> 'bad news'. This creates an irresistible curiosity gap because viewers expect glowing PR reviews.",
                hook_strength_score=98,
            ),
            retention_pacing=RetentionPacing(
                estimated_hook_retention_pct=91,
                dropoff_risk_timestamp="0:42",
                pacing_rhythm="Fast visual cuts every 2.2 seconds between first-person headset point-of-view and studio close-ups.",
                b_roll_frequency="12 visual cuts in first 40 seconds",
                why_viewers_stay="He promises to expose whether a $3,500 device gives you nausea and headache, which 99% of viewers cannot afford to test themselves.",
            ),
            director_script=[
                DirectorScriptRow(
                    timestamp="0:00 - 0:03",
                    camera_direction="Cinematic macro zoom on headset display eyes glowing. Creator sits motionless.",
                    dialogue="So... I just spent 24 straight hours with Apple's $3,500 computer strapped to my face.",
                    on_screen_text="24 HOURS INSIDE VISION PRO",
                    sound_fx="[Subtle electrical hum fades into heavy studio silence]",
                ),
                DirectorScriptRow(
                    timestamp="0:04 - 0:12",
                    camera_direction="Hard cut to studio wide angle. Creator takes off headset and rubs red marks on cheekbones.",
                    dialogue="And while the tech is genuinely magical... there are 3 things Apple's keynote conveniently didn't warn you about.",
                    on_screen_text="WHAT APPLE HID ⚠️",
                    sound_fx="[Hard thud as headset hits desk mat]",
                ),
                DirectorScriptRow(
                    timestamp="0:13 - 0:28",
                    camera_direction="Direct first-person POV shot: Floating 4K browser windows in physical living room.",
                    dialogue="Number one: The weight. After hour four, your neck feels like you've been carrying a bag of wet cement.",
                    on_screen_text="WEIGHT DISTORTION: 650g",
                    sound_fx="[Whoosh transition into immersive POV audio]",
                ),
                DirectorScriptRow(
                    timestamp="0:29 - 0:45",
                    camera_direction="Split-screen: Eye tracking demo vs physical eye twitch. Fast pacing.",
                    dialogue="Number two: The digital eyes on the outside look terrifying in dim light. Look at this comparison.",
                    on_screen_text="EXPECTATION VS REALITY 💀",
                    sound_fx="[Quick vinyl record scratch effect]",
                ),
            ],
            thumbnail_strategy=ThumbnailStrategy(
                recommended_text_overlay="DON'T BUY YET? (Yellow bold sans)",
                facial_expression_guide="Skeptical eyebrow raised, headset held halfway off face, high contrast studio lighting.",
                color_contrast_palette="Deep charcoal background, neon cyan headset glow, bold canary yellow typography.",
                high_ctr_logic="People fear wasting money on first-gen hardware. Asking a question with a doubtful look triggers FOMO and protection instincts.",
            ),
            multi_platform=MultiPlatformAssets(
                reel_caption="I wore Apple's Vision Pro for 24 hours straight without taking it off. Here is what Apple's marketing team didn't want you to see before spending $3,500. 🤯",
                hashtags=["#AppleVisionPro", "#TechReview", "#HardwareHonesty", "#MKBHDStyle"],
                twitter_thread=[
                    "1/7 I just spent 24 straight hours living inside Apple's Vision Pro.\n\nHere are 5 brutal truths about the $3,500 spatial computer no reviewer is telling you 🧵👇",
                    "2/7 The passthrough video is good, but in low light it looks like a 2012 webcam with motion blur. You cannot comfortably chop onions or read your phone screen with it on.",
                    "3/7 The battery pack in your pocket gets shockingly warm after 90 minutes of multitasking. And the cable snags on door handles constantly.",
                    "4/7 Typing on floating virtual keys is completely unusable for more than a 4-word reply. You MUST pair a physical Magic Keyboard.",
                    "5/7 The killer feature isn't movies or games. It's having 5 massive private screens on an airplane tray table without anyone next to you seeing your work.",
                    "6/7 Verdict: It's the most polished developer prototype in human history. But unless you're writing spatial apps, wait for Gen 3.",
                    "7/7 What would you use this for first? Let me know below and RT if this saved you $3,500.",
                ],
                linkedin_carousel_slides=[
                    {"slide": 1, "title": "Apple Vision Pro: 24 Hours Later", "body": "Why the $3,500 spatial computer is both a masterclass in UX and a cautionary tale in ergonomics."},
                    {"slide": 2, "title": "1. The Hardware Physics Trap", "body": "650 grams on human cheekbones cannot be solved with software updates. Extended wear fatigue is real."},
                    {"slide": 3, "title": "2. Gesture Input vs Keyboard Reality", "body": "Eye tracking + pinch feels like telekinesis for navigation. For knowledge workers, physical keyboards remain undefeated."},
                    {"slide": 4, "title": "3. The Social Isolation Index", "body": "EyeSight external display attempts to bridge human connection, but uncanny valley effects create social friction in shared spaces."},
                    {"slide": 5, "title": "The Strategic Takeaway", "body": "Apple is subsidizing developer ecosystem creation. V1 is for early adopters; V3 will redefine personal computing."},
                ],
            ),
            replication_concepts=[
                "Shoot a '24 Hours With [Product]' stress test challenging the most expensive gadget in your niche.",
                "Start with total silence or a heavy sigh rather than enthusiastic hype — shock the viewer's expectation.",
                "Demonstrate the 1 fatal flaw before praising the 5 good features to establish 100% viewer trust.",
            ],
            virality_breakdown=ViralityBreakdown(
                why_it_blew_up="Instead of standard tech hype, MKBHD used an extreme anti-hype pattern (silence -> heavy sigh -> 'bad news') on Apple's most hyped $3,500 gadget.",
                algorithmic_trigger="Achieved 91% hook retention and 78% average view duration, triggering YouTube's top tier browse recommendation.",
                psychological_hook="Negative anticipation on a luxury item creates extreme FOMO for non-owners.",
                retention_mechanic="POV spatial computing demonstration withholding the final verdict until the last 60 seconds.",
            ),
            next_viral_playbook=NextViralPlaybook(
                recommended_topic="Why I Stopped Using Apple's Vision Pro After 30 Days",
                exact_opening_line="One month ago, everyone called this the future of computing. Here is why it has been sitting in my drawer for two weeks.",
                visual_pattern_interrupt="Deadpan stare into lens holding up dusty headset, dropping it onto desk with a heavy thud.",
                retention_rule_to_apply="Keep visual stimulus resets under 2.2 seconds using A-roll to B-roll POV cuts.",
            ),
        ),
    ),

    "warikoo": ChannelDossierResponse(
        channel=ChannelProfile(
            handle="@warikoo",
            title="Ankur Warikoo",
            description="Entrepreneur, Author, Teacher. Financial freedom & brutal life truths.",
            avatar="https://yt3.ggpht.com/Xmf5LtdlD2A7hOScjvc0nh87d1YfbfF458lN7Ot5T1a1CQePP6vNEmhZuj0x0TSz-37DBMzUsw=s88-c-k-c0x00ffffff-no-rj",
            subscriber_count="7.13M",
            total_videos_analyzed=50,
            median_views=94000,
            formatted_median_views="94K",
            viral_breakout_rate="12.0%",
            niche="Personal Finance & Wealth Psychology",
        ),
        videos=[
            VideoItem(
                id="5TQEEGcOl70",
                title="Want to Buy a House? Do These 3 Things First",
                url="https://www.youtube.com/watch?v=5TQEEGcOl70",
                views=1420000,
                formatted_views="1.42M",
                thumbnail="https://i.ytimg.com/vi/5TQEEGcOl70/hqdefault.jpg",
                published_at="Mar 2024",
                is_short=False,
                outlier_score=15.1,
                is_outlier=True,
                is_mega_viral=True,
                outlier_badge="Mega Outlier 🚀 (15.1x)",
            ),
            VideoItem(
                id="ZVa_cBnzaOU",
                title="Your Body Has A Selling Price",
                url="https://www.youtube.com/watch?v=ZVa_cBnzaOU",
                views=640000,
                formatted_views="640K",
                thumbnail="https://i.ytimg.com/vi/ZVa_cBnzaOU/hqdefault.jpg",
                published_at="Jan 2024",
                is_short=False,
                outlier_score=6.8,
                is_outlier=True,
                is_mega_viral=True,
                outlier_badge="Mega Outlier 🚀 (6.8x)",
            ),
            VideoItem(
                id="NGRI92fetH4",
                title="Episode 1: Money Doesn't Behave",
                url="https://www.youtube.com/watch?v=NGRI92fetH4",
                views=240000,
                formatted_views="240K",
                thumbnail="https://i.ytimg.com/vi/NGRI92fetH4/hqdefault.jpg",
                published_at="Feb 2024",
                is_short=False,
                outlier_score=2.55,
                is_outlier=True,
                is_mega_viral=False,
                outlier_badge="Viral Breakout 🔥 (2.5x)",
            ),
            VideoItem(
                id="MBrGobP0M_g",
                title="Episode 2: The Deal Nobody Filmed",
                url="https://www.youtube.com/watch?v=MBrGobP0M_g",
                views=94000,
                formatted_views="94K",
                thumbnail="https://i.ytimg.com/vi/MBrGobP0M_g/hqdefault.jpg",
                published_at="Jan 2024",
                is_short=False,
                outlier_score=1.0,
                is_outlier=False,
                is_mega_viral=False,
                outlier_badge="Channel Median (1.0x)",
            ),
        ],
        top_outliers=[
            VideoItem(
                id="5TQEEGcOl70",
                title="Want to Buy a House? Do These 3 Things First",
                url="https://www.youtube.com/watch?v=5TQEEGcOl70",
                views=1420000,
                formatted_views="1.42M",
                thumbnail="https://i.ytimg.com/vi/5TQEEGcOl70/hqdefault.jpg",
                published_at="Mar 2024",
                is_short=False,
                outlier_score=15.1,
                is_outlier=True,
                is_mega_viral=True,
                outlier_badge="Mega Outlier 🚀 (15.1x)",
            ),
            VideoItem(
                id="ZVa_cBnzaOU",
                title="Your Body Has A Selling Price",
                url="https://www.youtube.com/watch?v=ZVa_cBnzaOU",
                views=640000,
                formatted_views="640K",
                thumbnail="https://i.ytimg.com/vi/ZVa_cBnzaOU/hqdefault.jpg",
                published_at="Jan 2024",
                is_short=False,
                outlier_score=6.8,
                is_outlier=True,
                is_mega_viral=True,
                outlier_badge="Mega Outlier 🚀 (6.8x)",
            ),
        ],
        active_dossier=VideoDossier(
            video=VideoItem(
                id="5TQEEGcOl70",
                title="Want to Buy a House? Do These 3 Things First",
                url="https://www.youtube.com/watch?v=5TQEEGcOl70",
                views=1420000,
                formatted_views="1.42M",
                thumbnail="https://i.ytimg.com/vi/5TQEEGcOl70/hqdefault.jpg",
                published_at="Mar 2024",
                is_short=False,
                outlier_score=15.1,
                is_outlier=True,
                is_mega_viral=True,
            ),
            hook_forensics=HookForensics(
                first_3_seconds_visual="Warikoo aggressively tearing a paper sheet labeled '₹75,00,000 HOME LOAN EMI' with a dark red lighting backdrop.",
                first_3_seconds_audio="\"Agar aapki umar 22 se 30 saal ke beech hai, toh aapke maa-baap aur relatives aapko ek aisi galti karne bol rahe hain jo aapko agle 20 saal tak gareeb rakhegi.\"",
                primary_psychological_trigger="Familial Taboo & Generational Wealth Trap",
                trigger_explanation="In India, buying a house is the #1 sacred dream pushed by parents. By calling it 'a trap that will keep you poor for 20 years with mathematical proof', he triggered massive emotional debate between traditional parents and ambitious youth.",
                hook_strength_score=99,
            ),
            retention_pacing=RetentionPacing(
                estimated_hook_retention_pct=94,
                dropoff_risk_timestamp="0:38",
                pacing_rhythm="Rapid animated spreadsheet overlays and compound interest calculation bars.",
                b_roll_frequency="Visual changes every 2.0 seconds",
                why_viewers_stay="Viewer wants to see if their parents' biggest financial advice is mathematically flawed.",
            ),
            director_script=[
                DirectorScriptRow(
                    timestamp="0:00 - 0:03",
                    camera_direction="Tight close-up shot, intense direct eye contact, tearing loan paper.",
                    dialogue="Agar aapki age 22 se 30 saal ke beech hai, toh ek galti aapko agle 20 saal tak gareeb rakhegi.",
                    on_screen_text="DON'T BUY A HOUSE YET ❌",
                    sound_fx="[Paper tearing sound + Bass drop boom]",
                ),
                DirectorScriptRow(
                    timestamp="0:04 - 0:15",
                    camera_direction="Camera pulls back to desk setup. Pulls out marker and whiteboard.",
                    dialogue="Aapke parents bolenge: 'Beta, EMI bharoge toh khud ka ghar hoga, rent toh waste of money hai.' Par math kuch aur kehta hai.",
                    on_screen_text="THE 'RENT IS WASTE' LIE?",
                    sound_fx="[Marker cap pop sound]",
                ),
                DirectorScriptRow(
                    timestamp="0:16 - 0:32",
                    camera_direction="Whiteboard calculation: ₹80 Lakh house = ₹65,000 EMI for 20 years = Total paid ₹1.56 Crore!",
                    dialogue="₹80 Lakh ke flat par aap 20 saal me ₹76 Lakh sirf bank ko INTEREST dete ho! Matlab ek flat apne liye khareeda, aur ek flat bank manager ke bacchon ke liye.",
                    on_screen_text="INTEREST: ₹76,00,000 PAID TO BANK",
                    sound_fx="[Cash register ka-ching followed by sad horn]",
                ),
                DirectorScriptRow(
                    timestamp="0:33 - 0:50",
                    camera_direction="Animated bar chart: Renting + SIP difference over 20 years = ₹3.4 Crores net worth!",
                    dialogue="Wahi ₹45,000 difference agar aapne Nifty 50 Index Fund me SIP kiya hota, toh 20 saal baad aapke paas ghar ke sath ₹3.4 Crore cash hota.",
                    on_screen_text="THE SIP COMPONENT: ₹3.4 CRORES",
                    sound_fx="[Ticking clock and triumphant bell chime]",
                ),
            ],
            thumbnail_strategy=ThumbnailStrategy(
                recommended_text_overlay="HOME LOAN IS A TRAP? (Red on Dark Grey)",
                facial_expression_guide="Serious warning expression, holding a miniature model house with a lock chain around it.",
                color_contrast_palette="Deep navy studio, blood red warning pill, bright white subtitle text.",
                high_ctr_logic="Contradicting traditional Indian middle-class pride creates explosive comment wars and shares on WhatsApp family groups.",
            ),
            multi_platform=MultiPlatformAssets(
                reel_caption="Why buying a flat on 20-year EMI in your 20s is mathematically the worst financial decision you will ever make. Read the calculation before signing that loan paper. 🏠❌",
                hashtags=["#PersonalFinanceIndia", "#HomeLoanReality", "#WarikooThoughts", "#MoneyMath"],
                twitter_thread=[
                    "1/6 In India, buying a house at 26 is considered 'settling down'.\n\nMathematically, it's the fastest way to kill your career mobility and stay middle class for 20 years.\n\nHere is the raw math your bank won't show you 🧵👇",
                    "2/6 Take an ₹80 Lakh flat in Bangalore or Gurgaon.\n\nDown payment: ₹16 Lakh.\nLoan: ₹64 Lakh @ 9% interest for 20 years.\nYour monthly EMI: ₹57,580.",
                    "3/6 Over 20 years, you pay:\nPrincipal: ₹64 Lakh\nInterest to Bank: ₹74.1 Lakh\nTotal Outflow: ₹1.38 Crore + maintenance + property tax.",
                    "4/6 If you rented that exact same flat for ₹25,000/month and invested the ₹32,580 difference into an index fund yielding 12%:\n\nAfter 20 years, your SIP corpus = ₹3.25 Crore cash.",
                    "5/6 At 45, you can buy that house in FULL CASH and still have ₹1.5 Crore left over for your children's education.",
                    "6/6 Share this with someone currently feeling FOMO because their friend just bought an apartment.",
                ],
                linkedin_carousel_slides=[
                    {"slide": 1, "title": "The 20-Year Home Loan Illusion", "body": "Why young Indian professionals are trading 2 decades of career risk for emotional brick-and-mortar."},
                    {"slide": 2, "title": "The Hidden Mathematics", "body": "At 9% interest over 240 months, you effectively buy 2 properties: one for yourself, and one for the lender's balance sheet."},
                    {"slide": 3, "title": "Opportunity Cost of Geolocation", "body": "A ₹60k EMI anchors you to one city. You cannot take a 50% pay hike in Dubai, Singapore, or a new startup."},
                    {"slide": 4, "title": "The Dual Wealth Formula", "body": "Disciplined renting + Index SIP creates 2.4x higher net liquid wealth by age 45 compared to home equity."},
                    {"slide": 5, "title": "When Should You Actually Buy?", "body": "When your down payment is >40%, EMI is <20% of household income, and you intend to live there for 15+ years."},
                ],
            ),
            replication_concepts=[
                "Take a widely accepted cultural advice in your niche and mathematically prove why it is outdated.",
                "Target the emotional tension between traditional parent expectations and modern career flexibility.",
                "Use the exact rupee amounts (₹80 Lakh, ₹76 Lakh interest) to make the pain tangible and shareable.",
            ],
            virality_breakdown=ViralityBreakdown(
                why_it_blew_up="Attacked India's biggest middle-class sacred cow ('Buying a house on 20-year EMI') with brutal mathematics, causing massive debate and shares across WhatsApp family groups.",
                algorithmic_trigger="Huge comment section velocity (agree vs disagree) within the first 2 hours pushed the video beyond subscribers to 1.42M viewers (15.1x channel average).",
                psychological_hook="Financial loss aversion: Proving that ₹76 Lakhs interest is gifted directly to the bank manager's kids.",
                retention_mechanic="Step-by-step whiteboard calculation where viewers stay to see the final SIP corpus comparison of ₹3.4 Crores.",
            ),
            next_viral_playbook=NextViralPlaybook(
                recommended_topic="Why Your Car EMI is Silently Stealing 5 Crores From Your Retirement",
                exact_opening_line="If you bought a car on loan to impress people you don't even like, here is the math that will keep you awake tonight.",
                visual_pattern_interrupt="Tearing a mock car loan brochure directly in front of the lens with a sharp paper-rip sound effect.",
                retention_rule_to_apply="Never reveal the SIP compounding alternative until scene 3; keep the cognitive curiosity gap open through scene 1 and 2.",
            ),
        ),
    ),

    "jeremy": ChannelDossierResponse(
        channel=ChannelProfile(
            handle="@JeremyEthier",
            title="Jeremy Ethier",
            description="Kinesiologist, science-based fitness and body transformation protocols.",
            avatar="https://yt3.googleusercontent.com/ytc/AIdro_k6B5d7u5u7f5y7=s176-c-k-c0x00ffffff-no-rj",
            subscriber_count="6.4M",
            total_videos_analyzed=38,
            median_views=420000,
            formatted_median_views="420K",
            viral_breakout_rate="7.8%",
            niche="Science-Based Hypertrophy & Fitness",
        ),
        videos=[
            VideoItem(
                id="outlier_jeremy_1",
                title="The ONLY 3 Exercises You Need For Massive Shoulders (Science-Backed)",
                url="https://www.youtube.com/watch?v=e_E12L8jXm8",
                views=3850000,
                formatted_views="3.85M",
                thumbnail="https://i.ytimg.com/vi/e_E12L8jXm8/hqdefault.jpg",
                published_at="May 2024",
                is_short=False,
                outlier_score=9.16,
                is_outlier=True,
                is_mega_viral=True,
                outlier_badge="Mega Outlier 🚀 (9.2x)",
            ),
            VideoItem(
                id="jeremy_2",
                title="Stop Doing Lateral Raises Like This (Shoulder Pain Fix)",
                url="https://www.youtube.com/watch?v=IODxDxX7oi4",
                views=1920000,
                formatted_views="1.92M",
                thumbnail="https://i.ytimg.com/vi/IODxDxX7oi4/hqdefault.jpg",
                published_at="Feb 2024",
                is_short=False,
                outlier_score=4.57,
                is_outlier=True,
                is_mega_viral=False,
                outlier_badge="Viral Breakout 🔥 (4.6x)",
            ),
            VideoItem(
                id="jeremy_3",
                title="How To Build Bigger Biceps (Fastest Way)",
                url="https://www.youtube.com/watch?v=3p8EGU9BvHQ",
                views=440000,
                formatted_views="440K",
                thumbnail="https://i.ytimg.com/vi/3p8EGU9BvHQ/hqdefault.jpg",
                published_at="Nov 2024",
                is_short=False,
                outlier_score=1.05,
                is_outlier=False,
                is_mega_viral=False,
                outlier_badge="Normal Baseline",
            ),
            VideoItem(
                id="jeremy_4",
                title="The Truth About 10,000 Steps A Day",
                url="https://www.youtube.com/watch?v=K0tN5B_67bY",
                views=390000,
                formatted_views="390K",
                thumbnail="https://i.ytimg.com/vi/K0tN5B_67bY/hqdefault.jpg",
                published_at="Sep 2024",
                is_short=False,
                outlier_score=0.93,
                is_outlier=False,
                is_mega_viral=False,
                outlier_badge="Normal Baseline",
            ),
        ],
        top_outliers=[
            VideoItem(
                id="outlier_jeremy_1",
                title="The ONLY 3 Exercises You Need For Massive Shoulders (Science-Backed)",
                url="https://www.youtube.com/watch?v=e_E12L8jXm8",
                views=3850000,
                formatted_views="3.85M",
                thumbnail="https://i.ytimg.com/vi/e_E12L8jXm8/hqdefault.jpg",
                published_at="May 2024",
                is_short=False,
                outlier_score=9.16,
                is_outlier=True,
                is_mega_viral=True,
                outlier_badge="Mega Outlier 🚀 (9.2x)",
            ),
        ],
        active_dossier=VideoDossier(
            video=VideoItem(
                id="outlier_jeremy_1",
                title="The ONLY 3 Exercises You Need For Massive Shoulders (Science-Backed)",
                url="https://www.youtube.com/watch?v=example_jeremy1",
                views=3850000,
                formatted_views="3.85M",
                thumbnail="https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=640&auto=format&fit=crop&q=80",
                published_at="May 2024",
                is_short=False,
                outlier_score=9.16,
                is_outlier=True,
                is_mega_viral=True,
                outlier_badge="Mega Outlier 🚀 (9.2x)",
            ),
            hook_forensics=HookForensics(
                first_3_seconds_visual="3D anatomical skeletal model with glowing neon green lateral deltoid fibers suddenly tearing under red stress simulation.",
                first_3_seconds_audio="\"If your shoulders still look flat after years of overhead pressing... you are targeting the completely wrong muscle head.\"",
                primary_psychological_trigger="Effort Invalidation & The Minimalist Shortcut",
                trigger_explanation="People work out for months without seeing capped shoulders. Telling them 'Your hard work is failing because of 1 anatomy mistake, and you only need 3 exercises' is the ultimate fitness click trigger.",
                hook_strength_score=96,
            ),
            retention_pacing=RetentionPacing(
                estimated_hook_retention_pct=88,
                dropoff_risk_timestamp="0:24",
                pacing_rhythm="Rapid alternating between 3D muscle anatomy and real gym execution form cues.",
                b_roll_frequency="Cut every 2.4 seconds",
                why_viewers_stay="Viewers want the 3 specific exercises so they can immediately modify their next workout.",
            ),
            director_script=[
                DirectorScriptRow(
                    timestamp="0:00 - 0:03",
                    camera_direction="Tight shot of 3D muscle skeleton showing glowing deltoid fibers.",
                    dialogue="If your shoulders still look narrow from the front, you are wasting 80% of your gym time on the wrong exercise.",
                    on_screen_text="STOP WASTING SHOULDER DAYS ⚠️",
                    sound_fx="[Heavy metallic dumbbell rack clank]",
                ),
                DirectorScriptRow(
                    timestamp="0:04 - 0:14",
                    camera_direction="Split-screen: Overhead Barbell Press vs Cable Lateral Raise EMG muscle activation graph.",
                    dialogue="Most guys think heavy overhead presses build wide shoulders. But EMG science proves the lateral head gets almost ZERO activation.",
                    on_screen_text="EMG ACTIVATION: ONLY 14%!",
                    sound_fx="[Heart monitor flatline buzz effect]",
                ),
                DirectorScriptRow(
                    timestamp="0:15 - 0:30",
                    camera_direction="Gym demo: Adjusting cable height to wrist level with 15-degree torso lean.",
                    dialogue="Exercise number 1: Behind-the-back cable lateral raise with a 15-degree lean. Watch what happens to the tension curve.",
                    on_screen_text="EXERCISE 1: BEHIND-BACK LEANING CABLE",
                    sound_fx="[Smooth cable pulley glide sound]",
                ),
            ],
            thumbnail_strategy=ThumbnailStrategy(
                recommended_text_overlay="ONLY 3 EXERCISES (Neon Lime Green)",
                facial_expression_guide="Red X over standard dumbbell press, Green Checkmark over cable lateral raise with deltoid highlighted.",
                color_contrast_palette="Charcoal gym backdrop, high-luminescence lime green anatomical fiber outline.",
                high_ctr_logic="The word 'ONLY 3' simplifies a complex workout routine into an achievable high-leverage protocol.",
            ),
            multi_platform=MultiPlatformAssets(
                reel_caption="Why your shoulders aren't growing despite heavy overhead pressing. The 3 science-backed movements you actually need for 3D capped deltoids. 💪🧬",
                hashtags=["#ShoulderWorkout", "#ScienceBasedFitness", "#Hypertrophy", "#GymTips"],
                twitter_thread=[
                    "1/5 Stop doing 6 different shoulder exercises in one workout.\n\nBiomechanics research shows 90% of lifters over-train their front delts and completely ignore the lateral head.\n\nHere are the ONLY 3 movements you need 🧵👇",
                    "2/5 Movement 1: Leaning Cable Lateral Raise\nWhy: Constant tension at the bottom of the movement where dumbbells have zero resistance. Lean forward 15 degrees to align with deltoid scapular plane.",
                    "3/5 Movement 2: Incline Dumbbell Rear Delt Row\nWhy: Elbows flared at 45 degrees targets the posterior head without upper trap takeover.",
                    "4/5 Movement 3: Standing Dumbbell Overhead Press (Progressive Overload)\nWhy: Stabilizer core engagement and anterior head strength.",
                    "5/5 Save this thread for your next push day. Which exercise was missing from your routine?",
                ],
                linkedin_carousel_slides=[
                    {"slide": 1, "title": "The Pareto Principle in Physical Training", "body": "How 3 high-leverage movements generate 85% of hypertrophy outcomes."},
                    {"slide": 2, "title": "The Overhead Press Misconception", "body": "Why heavy compound movements don't always align with optimal aesthetic muscle fiber recruitment."},
                    {"slide": 3, "title": "Resistance Curves Matter", "body": "Matching human strength curves with cable physics reduces joint wear while maximizing mechanical tension."},
                ],
            ),
            replication_concepts=[
                "Challenge the #1 sacred exercise in your industry and demonstrate the lower-effort, higher-yield alternative.",
                "Use high-contrast visual cues (Red X vs Green Checkmark) to communicate superiority in 0.5 seconds.",
                "Promise an 'ONLY X' minimalist framework to eliminate decision paralysis.",
            ],
            virality_breakdown=ViralityBreakdown(
                why_it_blew_up="Effort invalidation: Informed 6-day-a-week gym goers that their hardest exercise (overhead press) wasn't actually building wide shoulders.",
                algorithmic_trigger="88% retention at second 0:15 due to instant 3D anatomical skeletal animation showing muscle tear mechanics.",
                psychological_hook="Status protection: Gym goers desperately want to verify if they are wasting their time and injuring rotator cuffs.",
                retention_mechanic="The 'ONLY 3' rule created a closed list format where viewers must watch until #3 to complete the routine.",
            ),
            next_viral_playbook=NextViralPlaybook(
                recommended_topic="Stop Doing Crunches If You Want Six-Pack Abs (Do This 1 Move Instead)",
                exact_opening_line="If you have been doing 100 crunches every night and still have lower belly fat, you are training the wrong muscle layer.",
                visual_pattern_interrupt="Side-profile posture comparison with a red warning box over lumbar spine.",
                retention_rule_to_apply="Show 3D biomechanical animation within the first 6 seconds to establish undeniable scientific credibility.",
            ),
        ),
    ),
}
